## Ejercicios - pandas 4

In [123]:
import numpy as np
import pandas as pd

In [124]:
# Versiones

print(f"numpy=={np.__version__}")
print(f"pandas=={pd.__version__}")

numpy==2.2.0
pandas==2.2.3


#### En la siguiente celda se guarda la información del excel

In [125]:
df1 = pd.read_excel("./Data/Airbnb_NYC.xlsx", sheet_name = "NYC1")
df2 = pd.read_excel("./Data/Airbnb_NYC.xlsx", sheet_name = "NYC2")

### Ejercicio 0:
- Une los dos DataFrames anteriores por la columna **id**. Guarda en nuevo DataFrame en **df**

In [126]:
df = pd.merge(df1, df2)
df.head(2)

id                                name  host_id host_name  municipio  \
0  2539  Clean & quiet apt home by the park     2787      John   Brooklyn   
1  2595               Skylit Midtown Castle     2845  Jennifer  Manhattan   

       barrio  latitude  longitude        room_type  price  minimum_nights  \
0  Kensington  40.64749  -73.97237     Private room  149.0             1.0   
1     Midtown  40.75362  -73.98377  Entire home/apt  225.0             1.0   

   number_of_reviews last_review  reviews_per_month  \
0                9.0  2018-10-19               0.21   
1               45.0  2019-05-21               0.38   

   calculated_host_listings_count  availability_365  
0                             6.0             365.0  
1                             2.0             355.0

### Ejercicio 1:
- Si quiero hospedarme en Manhattan una sola noche y para elegir el Airbnb me guio por el que tenga el mayor número de reviews, ¿donde me debería de hospedar?

In [127]:
df1= df[(df["municipio"] == "Manhattan") & (df["minimum_nights"] == 1.0)]

In [128]:
df1.sort_values("number_of_reviews", ascending=False).head(1)

id                        name  host_id host_name  municipio  \
2031  903972  Great Bedroom in Manhattan  4734398        Jj  Manhattan   

      barrio  latitude  longitude     room_type  price  minimum_nights  \
2031  Harlem  40.82085  -73.94025  Private room   49.0             1.0   

      number_of_reviews last_review  reviews_per_month  \
2031              607.0  2019-06-21               7.75   

      calculated_host_listings_count  availability_365  
2031                             3.0             293.0

In [129]:
df["room_type"].unique()

array(['Private room', 'Entire home/apt', 'Shared room'], dtype=object)

### Ejercicio 2:
- Busco un Airbnb en el municipio donde el precio promedio de alquiler sea el más bajo y la cantidad de review por mes sea el mayor. ¿Cuáles son las 3 habitaciones que mejor se adaptan a estos criterios?

In [130]:
media_municipio = df.groupby('municipio')['price'].mean()
media_municipio.idxmin()

'Bronx'

In [131]:
df2= df[(df["room_type"] == "Private room") & (df["municipio"] == "Bronx")]

In [132]:
df2.sort_values("reviews_per_month", ascending=False).head(3)

id                                               name    host_id  \
42252  32801214         TW #6 Private Suite 2nd Fl.  1 to 4 Guests  211136294   
30579  23666777  LATE CHECK IN DISCOUNT! NO CLEANING FEE! 2/5 t...   82889379   
43806  33884349                    Comfy Bronx home away from home   54136018   

            host_name municipio         barrio  latitude  longitude  \
42252  Sharon & Erika     Bronx  Schuylerville  40.83560  -73.83369   
30579           Shera     Bronx       Woodlawn  40.89873  -73.86449   
43806          Louise     Bronx    Kingsbridge  40.86925  -73.89974   

          room_type  price  minimum_nights  number_of_reviews last_review  \
42252  Private room  150.0             1.0               24.0  2019-06-20   
30579  Private room   34.0             1.0              122.0  2019-06-28   
43806  Private room   35.0             1.0                8.0  2019-06-27   

       reviews_per_month  calculated_host_listings_count  availability_365  
42252               8.37                             5.0             247.0  
30579               8.24                             4.0               5.0  
43806               8.00                             1.0              48.0

### Ejercicio 3:
- Quiero rentar un Airbnb completo por un total de 200 días, en Brooklyn o Manhattan; no quiero pagar más de 150 dólares por noche, ¿Cuáles son las 5 opciones más economicas que me ofrece Airbnb?

In [133]:
df3= df[(df["availability_365"] >= 200) 
        & (df["room_type"] == "Entire home/apt") 
        & (df["price"] <= 150) 
        & (df["municipio"].isin(["Brooklyn", "Manhattan"]))]


In [134]:
df3.sort_values("price").head(5)

id                                              name    host_id  \
46049  35042058           Big one bedroom apt, new and beautiful.      19342   
20992  16620607           Spacious and Modern 2 Bedroom Apartment  109725962   
28517  22103438                                   Dee's Rest Easy  161468583   
25633  20523741  Cozy Mini Studio Prvt Bath & Kitchen 15 Mins JFK  141027957   
44560  34302049          Bright, cozy 1 bedroom near Central Park   17831516   

      host_name  municipio           barrio  latitude  longitude  \
46049     Rivka  Manhattan  Upper West Side  40.79900  -73.96315   
20992     Erika   Brooklyn         Bushwick  40.68994  -73.91556   
28517       Dee   Brooklyn         Flatbush  40.64429  -73.95732   
25633  Radhames   Brooklyn    Cypress Hills  40.69006  -73.86917   
44560   Rebecca  Manhattan      East Harlem  40.78728  -73.94710   

             room_type  price  minimum_nights  number_of_reviews last_review  \
46049  Entire home/apt   11.0             7.0                0.0         NaT   
20992  Entire home/apt   11.0             2.0              113.0  2019-06-22   
28517  Entire home/apt   22.0             2.0               35.0  2019-04-29   
25633  Entire home/apt   34.0             2.0               93.0  2019-06-30   
44560  Entire home/apt   35.0            30.0                0.0         NaT   

       reviews_per_month  calculated_host_listings_count  availability_365  
46049                NaN                             1.0             273.0  
20992               3.86                             1.0             261.0  
28517               1.83                             1.0             312.0  
25633               4.07                             2.0             247.0  
44560                NaN                             1.0             235.0

### Ejercicio 4:
- En un nuevo Dataframe muestra por municipio: el número de habitaciones tipo individual, casa o departamento entero y compartido; también muestra en otra columna el precio promedio de todas las habitaciones por municipio.

In [135]:
habitaciones_por_municipio = df.groupby(['municipio', 'room_type']).size().unstack(fill_value=0)

In [136]:
precio_promedio = df.groupby('municipio')['price'].mean()

In [137]:
resultado = pd.concat([habitaciones_por_municipio, precio_promedio], axis=1)
resultado.columns = list(habitaciones_por_municipio.columns) + ['precio_promedio']

In [138]:
resultado

Entire home/apt  Private room  Shared room  precio_promedio
municipio                                                                 
Bronx                      379           652           60        87.496792
Brooklyn                  9559         10132          413       124.383207
Manhattan                13199          7982          480       196.875814
Queens                    2096          3372          198        99.517649
Staten Island              176           188            9       114.812332

### Ejercicio 5:
- Crea una nueva columna en el DataFrame original, con el rating de acuerdo a la siguiente formula, donde las variables son: puntaje del municipio, número de reviews y disponibilidad de la habitación al año.

- Formula: Rating = (Puntaje de ciudad) + (número de review/ 629) + (disponibilidad / 365).

- El puntaje para cada ciudad es el siguiente {"Manhattan" : 10/10, "Brooklyn" : 8/10, "Queens" : 6/10, "Staten Island" : 4/10, "Bronx" : 2/10}.

In [139]:
puntaje = {"Manhattan" : 10/10, "Brooklyn" : 8/10, "Queens" : 6/10, "Staten Island" : 4/10, "Bronx" : 2/10}

In [140]:
def rating_df (x):
    puntaje_ciudad = puntaje.get(x["municipio"],0)
    reviews= x["number_of_reviews"] / 629
    disponibilidad = x["availability_365"] / 365
    rating = puntaje_ciudad + reviews + disponibilidad
    return rating

In [141]:
df['rating'] = df.apply(rating_df, axis=1)
df.head(1)

id                                name  host_id host_name municipio  \
0  2539  Clean & quiet apt home by the park     2787      John  Brooklyn   

       barrio  latitude  longitude     room_type  price  minimum_nights  \
0  Kensington  40.64749  -73.97237  Private room  149.0             1.0   

   number_of_reviews last_review  reviews_per_month  \
0                9.0  2018-10-19               0.21   

   calculated_host_listings_count  availability_365    rating  
0                             6.0             365.0  1.814308

### Ejercicio 6:
- Encuentra las 5 habitaciones de cada municipio con mayor rating.

In [143]:
df6= df[df["room_type"] == "Private room"]

In [147]:
df6.sort_values(["municipio", "rating"], ascending=[True, False]).groupby("municipio").head(5)

id                                               name   host_id  \
171       44096                                   Room with a View    190409   
1193     506575                   Bronx Room Near Yankees + Harlem   2001830   
11894   9260415                Comfy Room Near Bronx Zoo and NYBG!  48106825   
557      206071         Yankee Stadium Oasis 2 stops to Manhattan!     12221   
15793  12774885           Spacious, cozy bedroom in a private home  69507287   
4931    3533604                 Private Room in a two bedroom apt.   9510645   
5789    4218129                  Special OFFER on Airbnb NYC Room!  21641206   
1076     453094                    Bedroom with Garden at the Back    137814   
5724    4170460                 #1 Superhost Special Offer in NYC!  21641206   
137       31994                 Room with En Suite Bathroom & Deck    137814   
2030     903947                     Beautiful Bedroom in Manhattan   4734398   
2015     891117                       Private Bedroom in Manhattan   4734398   
2031     903972                         Great Bedroom in Manhattan   4734398   
195       51572                        Prime Location in Manhattan    237329   
225       58059                PRIVATE Room on Historic Sugar Hill    277379   
11759   9145202                            Room near JFK Queen Bed  47621202   
20403  16276632  Cozy Room Family Home LGA Airport NO CLEANING FEE  26432133   
1271     546383                   My Little Guest Room in Flushing   2680820   
8001    6157276                    Bright LARGE BED near Manhattan  23591164   
7086    5115372  Comfy Room Family Home LGA Airport NO CLEANING...  26432133   
256       63320                 D Private Che@p Room 2 Explore NYC    303939   
249       62452                     A SpeciaL!! Private Room in NY    303939   
251       62787                        C Private Room By The Ferry    303939   
13046   9882254                        Owl's Landing - Garden Room  50068597   
12777   9767864                            Owl's Landing- The Loft  50068597   

             host_name      municipio              barrio  latitude  \
171           Waundell          Bronx          Highbridge  40.83232   
1193   Jose And Ysaira          Bronx      Morris Heights  40.84937   
11894            Julia          Bronx      Pelham Gardens  40.86617   
557               Lori          Bronx   Concourse Village  40.82802   
15793            Sarah          Bronx           Wakefield  40.88871   
4931             Rylan       Brooklyn            Bushwick  40.70399   
5789          Veronica       Brooklyn  Bedford-Stuyvesant  40.69527   
1076          Waldemar       Brooklyn        Clinton Hill  40.68699   
5724          Veronica       Brooklyn  Bedford-Stuyvesant  40.69560   
137           Waldemar       Brooklyn        Clinton Hill  40.68730   
2030                Jj      Manhattan              Harlem  40.82124   
2015                Jj      Manhattan              Harlem  40.82264   
2031                Jj      Manhattan              Harlem  40.82085   
195                Lee      Manhattan             Chelsea  40.74859   
225              Agnes      Manhattan              Harlem  40.82510   
11759             Dona         Queens             Jamaica  40.66730   
20403         Danielle         Queens       East Elmhurst  40.76335   
1271             Linda         Queens            Flushing  40.75578   
8001            Angela         Queens       East Elmhurst  40.76664   
7086          Danielle         Queens       East Elmhurst  40.76374   
256           Lissette  Staten Island       Tompkinsville  40.63481   
249           Lissette  Staten Island       Tompkinsville  40.63536   
251           Lissette  Staten Island       Tompkinsville  40.63518   
13046             Alex  Staten Island           Stapleton  40.63516   
12777             Alex  Staten Island       Tompkinsville  40.63661   

       longitude     room_type  price  minimum_nights  number_of_reviews  \
171    -7

### Ejercicio 7:
- Crea un DataFrame con la cantidad de reviews de cada municipio de acuerdo a tipo de habitación.

### Ejercicio 8:
- Encuentra los 10 barrios con mayor precio por habitación individual.

### Ejercicio 9:
- Encuentra el barrio con mejor rating de cada municipio.

### Ejercicio 10:
- Del resultado anterio, selecciona los 2 barrios con el menor precio por "dep/casa completo".

In [16]:
################################################################################################################################